version: '2'

services:
  app:
    ports:
      - 8081:8081
    image: 'spring-seating'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - mongo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seating
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Grace@2002
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
          
  db:
    image: 'postgres'
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Grace@2002
      POSTGRES_DB: seating
  mongo:
    image: 'mongo'
    container_name: mongo
    ports:
      - 27017:27017
