spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/Seating-Management
      uri: mongodb+srv://anu102003:aN102003u$@cluster0.phobywc.mongodb.net/Seating-Management?retryWrites=true&w=majority&appName=Cluster0
  datasource:
    url: jdbc:postgresql://localhost:5432/seating
    username: postgres
    password: Grace@2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG